# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-30 16:33
from __future__ import unicode_literals

import blog.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170919_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('subscribed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='upload_file',
            field=models.FileField(default=False, upload_to='%Y/%m/', validators=[blog.validators.validate_file_extension]),
        ),
    ]
